"""Expand language column length to 64

Revision ID: 766bd31684ab
Revises: 
Create Date: 2025-06-23 18:47:02.700749

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '766bd31684ab'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('publications', schema=None) as batch_op:
        batch_op.alter_column('language',
               existing_type=sa.VARCHAR(length=8),
               type_=sa.String(length=64),
               existing_nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('publications', schema=None) as batch_op:
        batch_op.alter_column('language',
               existing_type=sa.String(length=64),
               type_=sa.VARCHAR(length=8),
               existing_nullable=True)

    # ### end Alembic commands ###
