"""Add ODLPublication table

Revision ID: b477da01baa1
Revises: 1daa8b9a2d1f
Create Date: 2025-06-24 15:54:33.739132

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b477da01baa1'
down_revision = '1daa8b9a2d1f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('odl_publications',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('data', sa.JSON(), nullable=False),
    sa.Column('feed_id', sa.Integer(), nullable=False),
    sa.Column('crawled_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['feed_id'], ['odl_feeds.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('odl_publications')
    # ### end Alembic commands ###
